### ISSUE TITLE
Kickass 1.60 - Not returning results properly

### ISSUE THREAD

**Issue by AnthonyBe** [MaurizioRicci/qBittorrent_search_engine#1]
I'm using the Kickass script v1.60 in qB 4.1.3 x64 with Python 3.7.0 on Windows 10.

The data returned by the Kickass script always includes some extra stuff appended to the end of the Torrent name as follows:

`<torrent name>Torrent sites: 1, Tags:TV,Video`

When I click on any of them to load I get errors like this:

```
---------------------------
Invalid torrent
---------------------------
Failed to load the torrent: C:\Users\Anthony\AppData\Local\Temp\tmpih28dyth.
Error: expected value (list, dict, int or string) in bencoded string
---------------------------
OK   
---------------------------

```

**Comment by RogueScholar** [comment]
Experiencing the same malfunction with the Kickass plugin using qB 4.2.0alpha with Python 3.6.7rc1 on Ubuntu 18.04.1 Bionic Beaver

**Comment by MaurizioRicci** [comment]
I should have fixed it, it just that kickass often changes his domain
