### ISSUE TITLE
Various qBittorrent plugins not working

### ISSUE THREAD

**Issue by gumpster2010** [MaurizioRicci/qBittorrent_search_engine#2]
Hello MaurizioRicci --

I have been trying to use qBittorrent search and have noticed that a number of plugins don't seem to be producing any results (even for searches that I know have results listed online). 

The plugins I'm having issues with are: 

ETTV
ExtraTorrent
Kickass Torrents
TorrentFunk

So have it, I am running qBittorrent 4.1.0.  I was running 4.1.3 but I noticed many plugins seemed incompatible with that one, so I returned to a prior version (which should be working according to the Unofficial search plugins list). 

Please let me know if I'm onto something or if it's more likely a problem with my install. 

Thanks!
Ian

**Comment by Diezi** [comment]
I have the same problem! It seems to be a problem with Qbittorrent. I am actually using v 4.1.4

**Comment by MaurizioRicci** [comment]
-ETTV, ExtraTorrent are working for me.
-Kickass it's now fixed (they changed domain, they often do that)
-TorrentFunk looks like they have the search broken
